# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ftputils}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Bruz Marzolf"]
  s.date = %q{2011-04-19}
  s.description = %q{Implements a subset of the methods in FileUtils for FTP URIs, falling back on FileUtils when a path doesn't look like FTP}
  s.email = %q{bmarzolf@systemsbiology.org}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/ftputils.rb",
    "lib/ftputils/ext/class.rb",
    "lib/ftputils/ftpconnection.rb",
    "lib/ftputils/ftpfile.rb",
    "lib/ftputils/ftpuri.rb",
    "spec/ftpconnection_spec.rb",
    "spec/ftpfile_spec.rb",
    "spec/ftpuri_spec.rb",
    "spec/ftputils_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/bmarzolf/ftputils}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Like FileUtils for FTP}
  s.test_files = [
    "spec/ftpconnection_spec.rb",
    "spec/ftpfile_spec.rb",
    "spec/ftpuri_spec.rb",
    "spec/ftputils_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ftpfxp>, [">= 0.0.4"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<ftpfxp>, [">= 0.0.4"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<ftpfxp>, [">= 0.0.4"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

